# This workflow will install Python dependencies and run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install project
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install .[tests,mpi]

    - name: Test with pytest
      run: |
        mkdir pytest_dir
        cd pytest_dir
        py.test py2vtk -m "serial"

    - name: Remove test directory
      run: |
        rm -rf pytest_dir
